# Pizza API

## To use these HTTP endpoint install the REST Client plugin in VSCode.

### Get all the Pizzas from the API

GET https://pizza-api.projectcodex.net/api/pizzas

### Create a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=yousha-waja


### Get a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/BKGUIbr8Ou/get

### Add a pizza to the cart
 
POST https://pizza-api.projectcodex.net/api/pizza-cart/add
content-type: application/json

{
	"cart_code" : "BKGUIbr8Ou",
	"pizza_id" : 9
}

### Add a pizza to the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
content-type: application/json

{
	"cart_code" : "BKGUIbr8Ou`",
	"pizza_id" : 9
}

### Remove a pizza from the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/remove
content-type: application/json

{
	"cart_code" : "4sRvA0bX5M",
	"pizza_id" : 3
}

### GET all the carts for a given user

GET https://pizza-api.projectcodex.net/api/pizza-cart/username/yousha-waja

### GET all the active carts for a user

GET https://pizza-api.projectcodex.net/api/pizza-cart/username/yousha-waja/active


### Pay for a pizza from the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/pay	
content-type: application/json

{
	"cart_code" : "6o9Pu4u8zB",
	"amount" : 200
}


